AppLaundry/AppLaundry/Controllers/DaftarHargaController.cs
using AppLaundry.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppLaundry.Controllers
{
    public class DaftarHargaController : Controller
    {
        LaundryEntities DB = new LaundryEntities();

        // GET: Karyawan
        public ActionResult Index()
        {
            return View();
        }


        public JsonResult ListDaftarHarga()
        {

            PaginationDaftarHarga _pgDaftarHarga = new PaginationDaftarHarga();

            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();


                // paging
                //Paging Size (10,20,50,100)    
                int pageSize = length != null ? Convert.ToInt32(length) : 0;

                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;


                // Getting all Customer data    
                var _daftar_harga = DB.view_daftar_harga.ToList();


                //Sorting    
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortDir)))
                {
                    //_karyawan = _karyawan.OrderBy(sortColumn + " " + sortDir);
                }

                //Search    
                if (!string.IsNullOrEmpty(searchValue))
                {
                    //_karyawan = _karyawan.Where(m => m.karyawan_alamat == searchValue);
                }


                //total number of rows count     
                recordsTotal = _daftar_harga.Count();

                var data = _daftar_harga.Skip(skip).Take(pageSize).ToList();

                _pgDaftarHarga.draw = Convert.ToInt32(draw);
                _pgDaftarHarga.recordsFiltered = recordsTotal;
                _pgDaftarHarga.recordsTotal = recordsTotal;
                _pgDaftarHarga.data = data;

            }
            catch (Exception ex)
            {

                string message = ex.Message;
            }


            return Json(_pgDaftarHarga, JsonRequestBehavior.AllowGet);
        }



        public JsonResult UpdateDaftarHarga(FormCollection form)
        {
            ResponsesDaftarHarga _pgDaftarHarga = new ResponsesDaftarHarga();

            try
            {

                tbl_daftar_harga _tbl_daftar_harga = new tbl_daftar_harga()
                {
                    daftar_harga_id = Guid.Parse(form["daftar_harga_id"].ToString()),
                    daftar_harga_satuan = form["daftar_harga_satuan"].ToString(),
                    daftar_harga_nama = form["daftar_harga_nama"].ToString(),
                    daftar_harga_harga = Convert.ToInt32(form["daftar_harga_harga"].ToString()),

                };


                DB.Entry(_tbl_daftar_harga).State = EntityState.Modified;

                int result = DB.SaveChanges();

                if (result > 0)
                {

                    _pgDaftarHarga.Message = "Berhasil mengubah data";
                    _pgDaftarHarga.Status = false;
                    _pgDaftarHarga.Data = DB.view_daftar_harga.Where(x => x.daftar_harga_id == _tbl_daftar_harga.daftar_harga_id).SingleOrDefault();

                }
            }
            catch (Exception ex)
            {

                _pgDaftarHarga.Message = ex.Message;
                _pgDaftarHarga.Status = false;
                _pgDaftarHarga.Data = null;
            }


            return Json(_pgDaftarHarga, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult InsertDaftarHarga(FormCollection form)
        {

            ResponsesDaftarHarga _pgDaftarHarga = new ResponsesDaftarHarga();


            try
            {
                tbl_daftar_harga _tbl_daftar_harga = new tbl_daftar_harga()
                {
                    daftar_harga_id = Guid.NewGuid(),
                    daftar_harga_satuan = form["daftar_harga_satuan"].ToString(),
                    daftar_harga_nama = form["daftar_harga_nama"].ToString(),
                    daftar_harga_harga = Convert.ToInt32(form["daftar_harga_harga"].ToString()),
                };

                DB.tbl_daftar_harga.Add(_tbl_daftar_harga);
                DB.SaveChanges();

                _pgDaftarHarga.Message = "Berhasil menyimpan data";
                _pgDaftarHarga.Status = true;
                _pgDaftarHarga.Data = DB.view_daftar_harga.Where(x => x.daftar_harga_id == _tbl_daftar_harga.daftar_harga_id).SingleOrDefault();

            }
            catch (Exception ex)
            {
                _pgDaftarHarga.Message = ex.Message;
                _pgDaftarHarga.Status = false;
                _pgDaftarHarga.Data = null;

            }

            return Json(_pgDaftarHarga, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetDaftarHargaById(FormCollection form)
        {
            ResponsesDaftarHarga _pgDaftarHarga = new ResponsesDaftarHarga();



            try
            {
                Guid daftar_harga_id = Guid.Parse(form["daftar_harga_id"].ToString());

                int rowCount = DB.view_daftar_harga.Where(x => x.daftar_harga_id == daftar_harga_id).Count();

                if (rowCount > 0)
                {
                    _pgDaftarHarga.Message = "Data ditemukan";
                    _pgDaftarHarga.Status = true;
                    _pgDaftarHarga.Data = DB.view_daftar_harga.Where(x => x.daftar_harga_id == daftar_harga_id).SingleOrDefault();

                }


            }
            catch (Exception ex)
            {

                _pgDaftarHarga.Message = ex.Message;
                _pgDaftarHarga.Status = false;
                _pgDaftarHarga.Data = null;
            }

            return Json(_pgDaftarHarga, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult DeleteDaftarHarga(FormCollection form)
        {
            ResponsesDaftarHarga _pgDaftarHarga = new ResponsesDaftarHarga();
            try
            {
                Guid daftar_harga_id = Guid.Parse(form["daftar_harga_id"].ToString());

                tbl_daftar_harga _tbl_daftar_harga = DB.tbl_daftar_harga.Find(daftar_harga_id);

                if (_tbl_daftar_harga != null)
                {
                    DB.tbl_daftar_harga.Remove(_tbl_daftar_harga);
                    int result = DB.SaveChanges();

                    if (result > 0)
                    {
                        _pgDaftarHarga.Message = "Berhasil menghapus data.";
                        _pgDaftarHarga.Status = true;
                        _pgDaftarHarga.Data = null;
                    }
                    else
                    {
                        _pgDaftarHarga.Message = "Gagal menghapus data.";
                        _pgDaftarHarga.Status = false;
                        _pgDaftarHarga.Data = null;
                    }
                }
            }
            catch (Exception ex)
            {

                _pgDaftarHarga.Message = ex.Message;
                _pgDaftarHarga.Status = false;
                _pgDaftarHarga.Data = null;
            }

            return Json(_pgDaftarHarga, JsonRequestBehavior.AllowGet);
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                DB.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppLaundry/AppLaundry/Views/DaftarHarga/Index.cshtml
@{
    ViewBag.Title = "Daftar Harga";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row tm-content-row tm-mt-big">
    <div class="col-xl-12 col-lg-12 tm-md-12 tm-sm-12 tm-col">
        <div class="bg-white tm-block h-100">
            <div class="row">
                <div class="col-md-8 col-sm-12">
                    <h2 class="tm-block-title d-inline-block">Daftar Harga</h2>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <ul class="nav nav-tabs" id="tabsDaftarHargaHead" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="list-tab" data-toggle="tab" href="#panelList" role="tab" aria-controls="home" aria-selected="true">List Daftar Harga</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="form-tab" data-toggle="tab" href="#panelFormInsert" role="tab" aria-controls="profile" aria-selected="false">Form Daftar Harga</a>
                        </li>
                        <li class="nav-item">
                            <div class="pull-right">
                                <a href="Javascript:void(0);" class="nav-link" onclick="initInsertFormDaftarHarga();">Tambah Daftar Harga</a>
                            </div>

                        </li>
                    </ul>
                </div>

            </div>
            <div class="row" style="margin-top:20px;">
                <div class="col-sm-12">
                    <div class="tab-content" id="tabsDaftarHargaContent">
                        <div class="tab-pane fade show active" id="panelList" role="tabpanel" aria-labelledby="List">

                            <div class="table-responsive">
                                <table id="tblDaftarHarga" class="display table table-hover table-striped tm-table-striped-even mt-3" style="width:100%;">
                                    <thead>
                                        <tr class="tm-bg-gray">
                                            <th scope="col">&nbsp;</th>
                                            <th scope="col">Nama Daftar</th>
                                            <th scope="col" class="text-center">Harga</th>
                                            <th scope="col" class="text-center">Satuan</th>
                                            <th scope="col">&nbsp;</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>

                        </div>

                        <div class="tab-pane fade" id="panelFormInsert" role="tabpanel" aria-labelledby="Form">

                            <form action="#" class="tm-edit-product-form" id="formDaftarHarga" method="post">
                                <input type="hidden" name="daftar_harga_id" id="daftar_harga_id" />
                                <div class="input-group mb-3">
                                    <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">
                                        Nama Daftar
                                    </label>
                                    <input id="daftar_harga_nama" name="daftar_harga_nama" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7">
                                </div>
                                <div class="input-group mb-3">
                                    <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">
                                        Harga
                                    </label>
                                    <input id="daftar_harga_harga" name="daftar_harga_harga" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7">
                                </div>

                                <div class="input-group mb-3">
                                    <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">
                                        Satuan
                                    </label>
                                    <input id="daftar_harga_satuan" name="daftar_harga_satuan" type="text" class="form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7">
                                </div>


                                <div class="input-group mb-3">
                                    <div class="ml-auto col-xl-8 col-lg-8 col-md-8 col-sm-7 pl-0">
                                        <button type="submit" id="btn-submit-daftar-harga" class="btn btn-primary">
                                            Simpan
                                        </button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>





@section link_section{


    <!--

    Template 2108 Dashboard

    http://www.tooplate.com/view/2108-dashboard

    -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <!-- https://fonts.google.com/specimen/Open+Sans -->
    <link rel="stylesheet" href="~/Assets/theme/css/fontawesome.min.css">
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href="~/Assets/theme/css/bootstrap.min.css">
    <!-- https://getbootstrap.com/ -->
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    <!-- https://datatables.net/ -->
    <link rel="stylesheet" href="~/Assets/theme/css/tooplate.css">

}


@section script_section{

    <script src="~/Assets/theme/js/jquery-3.3.1.min.js"></script>
    <!-- https://jquery.com/download/ -->
    <script src="~/Assets/theme/js/bootstrap.min.js"></script>
    <!-- https://getbootstrap.com/ -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <!-- https://datatables.net/ -->




    <script>
        var table;

        $(document).ready(function () {
            table = $('#tblDaftarHarga').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    url: "@Url.Action("ListDaftarHarga","DaftarHarga")",
                    type: "POST"
                },
                "language": {
                    "search": "",
                    "searchPlaceholder": "Search..."
                },
                "columns": [
                    { "data": "daftar_harga_id" },
                    { "data": "daftar_harga_nama" },
                    { "data": "daftar_harga_harga" },
                    { "data": "daftar_harga_satuan" },
                    {
                        "data": "daftar_harga_id",
                        "className": "text-center",
                        "render": function (data, type, row) {
                            return '<button type="button" class="btn btn-warning" onClick="getDaftarHargaById(\'' + data + '\');initUpdateFormDaftarHarga();"> Edit </button>&nbsp;<button type="button" class="btn btn-danger" onClick="deleteDaftarHarga(\'' + data + '\');"> Delete </button>';
                        }
                    }
                ]

            });


            $('#formDaftarHarga').on('submit', function (e) {

                var daftar_harga_id = $('#daftar_harga_id').val();


                if (daftar_harga_id === "") {

                    insertDaftarHarga();

                } else {
                    updateDaftarHarga();
                }

                e.preventDefault();
            });


            $('#list-tab').on('click', function (e) {

                table.ajax.reload();

            });



        });




        function insertDaftarHarga() {

            var result = confirm("Apakah ingin menambah data ?");

            if (result) {


                $.ajax({
                    type: 'POST',
                    url: "@Url.Action("InsertDaftarHarga", "DaftarHarga")",
                    dataType: "json",
                    data: {
                        daftar_harga_id: $('#daftar_harga_id').val(),
                        daftar_harga_nama: $('#daftar_harga_nama').val(),
                        daftar_harga_harga: $('#daftar_harga_harga').val(),
                        daftar_harga_satuan: $('#daftar_harga_satuan').val(),
                    },
                    success: function (data) {
                        if (data.Status === true) {

                            alert(data.Message);

                        } else {

                            alert(data.Message);

                        }
                    }
                });


                initClearForm();
            }

        }


        function updateDaftarHarga() {

            var result = confirm("Apakah ingin mengubah data ?");

            if (result) {

                $.ajax({
                    type: 'POST',
                    url: "@Url.Action("UpdateDaftarHarga", "DaftarHarga")",
                    dataType: "json",
                    data: {
                        daftar_harga_id: $('#daftar_harga_id').val(),
                        daftar_harga_nama: $('#daftar_harga_nama').val(),
                        daftar_harga_harga: $('#daftar_harga_harga').val(),
                        daftar_harga_satuan: $('#daftar_harga_satuan').val(),
                    },
                    success: function (data) {
                        if (data.Status === true) {

                            alert(data.Message);

                        } else {

                            alert(data.Message);

                        }
                    }
                });

            }

        }


        function deleteDaftarHarga(daftar_harga_id) {

            var result = confirm("Apakah ingin menhhapus data ?");


            if (result) {

                $.ajax({
                    type: 'POST',
                    url: "@Url.Action("DeleteDaftarHarga", "DaftarHarga")",
                    dataType: "json",
                    data: {
                        daftar_harga_id: daftar_harga_id
                    },
                    success: function (data) {

                        if (data.Status === true) {

                            alert(data.Message);
                            table.ajax.reload();

                        } else {
                            alert(data.Message);
                        }

                    }
                });

            }


        };


        function getDaftarHargaById(daftar_harga_id) {

            initInsertFormDaftarHarga();


            $.ajax({
                type: 'POST',
                url: "@Url.Action("GetDaftarHargaById", "DaftarHarga")",
                dataType: "json",
                data: {
                    daftar_harga_id: daftar_harga_id
                },
                success: function (data) {

                    if (data.Status === true) {

                        alert(data.Message);

                        $('#daftar_harga_id').val(data.Data["daftar_harga_id"]);
                        $('#daftar_harga_nama').val(data.Data["daftar_harga_nama"]);
                        $('#daftar_harga_harga').val(data.Data["daftar_harga_harga"]);
                        $('#daftar_harga_satuan').val(data.Data["daftar_harga_satuan"]);


                    } else {

                        alert(data.Message);

                    }



                }
            });



        }


        function initInsertFormDaftarHarga() {

            $('#form-tab').trigger('click');

            $('#btn-submit-daftar-harga').text("Simpan");

            initClearForm();

        }


        function initUpdateFormDaftarHarga() {

            $('#btn-submit-daftar-harga').text("Update");
        }


        function initClearForm() {

            $('#formDaftarHarga').trigger('reset');

        };





    </script>

}