AppLaundry/AppLaundry/Controllers/TransaksiController.cs
using AppLaundry.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppLaundry.Controllers
{
    public class TransaksiController : Controller
    {

        LaundryEntities DB = new LaundryEntities();

        // GET: Transaksi
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult CucianMasuk()
        {
            return View();
        }


        public JsonResult ListCucianMasuk()
        {

            PaginationTransaksi _pgTransaksi = new PaginationTransaksi();
            List<view_transaksi> _viewTransaksi = new List<view_transaksi>();
            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();


                // paging
                //Paging Size (10,20,50,100)    
                int pageSize = length != null ? Convert.ToInt32(length) : 0;

                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = DB.view_transaksi.Count();

                int recordsFiltered = 0;


                // Getting all Customer data    
                //Search    
                if (!string.IsNullOrEmpty(searchValue))
                {
                    _viewTransaksi = DB.view_transaksi.Where(m => m.transaksi_status.Contains(searchValue)).ToList();
                }else
                {
                    _viewTransaksi = DB.view_transaksi.ToList();
                }

                //Sorting    
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortDir)))
                {
                    //_karyawan = _karyawan.OrderBy(sortColumn + " " + sortDir);
                }




                //total number of rows count     
                recordsFiltered = _viewTransaksi.Count();

                var data = _viewTransaksi.Skip(skip).Take(pageSize).ToList();

                _pgTransaksi.draw = Convert.ToInt32(draw);
                _pgTransaksi.recordsFiltered = recordsFiltered;
                _pgTransaksi.recordsTotal = recordsTotal;
                _pgTransaksi.data = data;

            }
            catch (Exception ex)
            {

                string message = ex.Message;
            }


            return Json(_pgTransaksi, JsonRequestBehavior.AllowGet);
        }



        public ActionResult CucianMasukBaru()
        {
            return View();
        }


        public ActionResult CucianKeluar()
        {
            return View();
        }



        public ActionResult KlaimCucian()
        {
            return View();
        }


    }
}

AppLaundry/AppLaundry/Views/Transaksi/CucianKeluar.cshtml
@{
    ViewBag.Title = "CucianKeluar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="container" style="margin-top: 50px;background-color:#ffffff;padding:50px;">
    <div class="row">
        <div class="col-lg-12">
            <h3>List Cucian Keluar</h3>
        </div>
    </div>

 

</div>



@section link_section{


    <!--

    Template 2108 Dashboard

    http://www.tooplate.com/view/2108-dashboard

    -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <!-- https://fonts.google.com/specimen/Open+Sans -->
    <link rel="stylesheet" href="~/Assets/theme/css/fontawesome.min.css">
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href="~/Assets/theme/css/bootstrap.min.css">
    <!-- https://getbootstrap.com/ -->

    <link rel="stylesheet" href="~/Assets/theme/css/tooplate.css">

}


@section script_section{

    <script src="~/Assets/theme/js/jquery-3.3.1.min.js"></script>
    <!-- https://jquery.com/download/ -->
    <script src="~/Assets/theme/js/bootstrap.min.js"></script>
    <!-- https://getbootstrap.com/ -->




}

AppLaundry/AppLaundry/Views/Transaksi/CucianMasuk.cshtml
@{
    ViewBag.Title = "CucianMasuk";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="container" style="margin-top: 50px;background-color:#ffffff;padding:50px;">
    <div class="row">
        <div class="col-lg-12">
            <h3>List Cucian Masuk</h3>
        </div>
    </div>

    <div class="row" style="margin-top:25px;">
        <div class="col-lg-12">
            <div class="pull-right">
                <a href="@Url.Action("CucianMasukBaru","Transaksi")" class="btn btn-block btn-sm btn-primary">Transaksi Baru</a>
            </div>
        </div>

        <div class="col-lg-12" style="margin-top:25px;">

            <div class="table-responsive">
                <table id="tblCucianMasuk" class="display table table-hover table-striped tm-table-striped-even mt-3" style="width:100%;">
                    <thead>
                        <tr class="tm-bg-gray">
                            <th scope="col">Date</th>
                            <th scope="col">Nama</th>
                            <th scope="col">Status</th>
                            <th scope="col" class="text-center">Total</th>
                            <th scope="col">#</th>
                        </tr>
                    </thead>
                </table>
            </div>

        </div>
    </div>

</div>



@section link_section{


    <!--

    Template 2108 Dashboard

    http://www.tooplate.com/view/2108-dashboard

    -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <!-- https://fonts.google.com/specimen/Open+Sans -->
    <link rel="stylesheet" href="~/Assets/theme/css/fontawesome.min.css">
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href="~/Assets/theme/css/bootstrap.min.css">
    <!-- https://getbootstrap.com/ -->
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    <!-- https://datatables.net/ -->
    <link rel="stylesheet" href="~/Assets/theme/css/tooplate.css">

}


@section script_section{

    <script src="~/Assets/theme/js/jquery-3.3.1.min.js"></script>
    <!-- https://jquery.com/download/ -->
    <script src="~/Assets/theme/js/bootstrap.min.js"></script>
    <!-- https://getbootstrap.com/ -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <!-- https://datatables.net/ -->


    <script>
        var table;

        $(document).ready(function () {
            table = $('#tblCucianMasuk').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    url: "@Url.Action("ListCucianMasuk","Transaksi")",
                    type: "POST"
                },
                "language": {
                    "search": "",
                    "searchPlaceholder": "Search..."
                },
                "columns": [
                    { "data": "transaksi_datetime" },
                    { "data": "pelanggan_nama" },
                    { "data": "transaksi_status" },
                    { "data": "transaksi_total" },
                    {
                        "data": "transaksi_id",
                        "className": "text-center",
                        "render": function (data, type, row) {
                            return '<button type="button" class="btn btn-warning" onClick="getKaryawanById(\'' + data + '\');initUpdateFormKaryawan();"> Edit </button>&nbsp;<button type="button" class="btn btn-danger" onClick="deleteKaryawan(\'' + data + '\');"> Delete </button>';
                        }
                    }
                ]

            });


        });



    </script>

}

AppLaundry/AppLaundry/Views/Transaksi/CucianMasukBaru.cshtml
@{
    ViewBag.Title = "CucianMasukBaru";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="margin-top: 50px;background-color:#ffffff;padding:10px;">
    <div class="row">
        <div class="col-lg-4">
            <div class="alert alert-info pd-info">No Transaksi</div>
            <div class="form-group form-group-height">
                <label>No Transaksi</label>
                <input class="form-control input-sm" type="text" />
            </div>
        </div>

        <div class="col-lg-4">
            <div class="alert alert-info pd-info">Data Pelanggan</div>
            <div class="form-group form-group-height">
                <label>Nama Pelanggan</label>
                <input class="form-control" type="text" />
            </div>
        </div>

        <div class="col-lg-4">
            <div class="alert alert-info pd-info">Tanggal Transaksi</div>
            <div class="form-group form-group-height">
                <label>Tanggal Terima</label>
                <input class="form-control" type="text" />
            </div>

        </div>

    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-info pd-info">Enter Transaksi</div>
        </div>
        <div class="col-lg-4">
            <div class="form-group form-group-height">
                <label>Nama Item</label>
                <input class="form-control" type="text" />
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-group form-group-height">
                <label>Jumlah</label>
                <input class="form-control" type="text" />
            </div>
        </div>
        <div class="col-lg-2">
            <div class="form-group form-group-height">
                <label>Satuan</label>
                <input class="form-control" type="text" />
            </div>
        </div>
        <div class="col-lg-2">
            <div class="form-group form-group-height">
                <button type="submit" class="btn btn-sm">Add To List</button>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-8">
            <div class="alert alert-info pd-info">List laundry item</div>
        </div>

        <div class="col-lg-4">
            <div class="alert alert-info pd-info">Pembayaran Total</div>
        </div>
        <div class="col-lg-8">
            <div class="table-responsive">
                <table id="tblCucianMasuk" class="display table table-hover table-striped tm-table-striped-even mt-3" style="width:100%;">
                    <thead>
                        <tr class="tm-bg-gray">
                            <th scope="col">

                            </th>
                            <th scope="col">Nama</th>
                            <th scope="col">Status</th>
                            <th scope="col" class="text-center">Total</th>
                            <th scope="col">#</th>
                        </tr>
                    </thead>
                </table>
            </div>

        </div>
        <div class="col-lg-4">
            <div class="form-group form-group-height">
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-8"></div>
            
        </div>

</div>



@section link_section{


    <!--

    Template 2108 Dashboard

    http://www.tooplate.com/view/2108-dashboard

    -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <!-- https://fonts.google.com/specimen/Open+Sans -->
    <link rel="stylesheet" href="~/Assets/theme/css/fontawesome.min.css">
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href="~/Assets/theme/css/bootstrap.min.css">
    <!-- https://getbootstrap.com/ -->
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    <!-- https://datatables.net/ -->
    <link rel="stylesheet" href="~/Assets/theme/css/tooplate.css">

    <style>
        .pd-info {
            padding: 2px 0px;
        }

        .form-group-height {
            line-height: 0px !important;
        }

            .form-group-height label {
                margin-bottom: 12px !important;
            }

            .form-group-height input {
                height: 0px !important;
                padding: 12px 12px;
            }

            .form-group-height button {
                padding: 12px 10px !important;
                border-radius: 28% !important;
                background-color: #77bf6a;
                color: #fff;
                font-weight: bold;
            }
    </style>

}


@section script_section{

    <script src="~/Assets/theme/js/jquery-3.3.1.min.js"></script>
    <!-- https://jquery.com/download/ -->
    <script src="~/Assets/theme/js/bootstrap.min.js"></script>
    <!-- https://getbootstrap.com/ -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <!-- https://datatables.net/ -->


    <script>
        var table;

        $(document).ready(function () {
            table = $('#tblCucianMasuk').DataTable({
                "processing": true,
                "serverSide": true,
                "info": false,
                "paging": false,
                "searching": false,
                "ajax": {
                    url: "@Url.Action("ListCucianMasuk","Transaksi")",
                    type: "POST"
                },
                "columns": [
                    { "data": "transaksi_datetime" },
                    { "data": "pelanggan_nama" },
                    { "data": "transaksi_status" },
                    { "data": "transaksi_total" },
                    {
                        "data": "transaksi_id",
                        "className": "text-center",
                        "render": function (data, type, row) {
                            return '<button type="button" class="btn btn-warning" onClick=""> Edit </button>&nbsp;<button type="button" class="btn btn-danger" onClick=""> Delete </button>';
                        }
                    }
                ]

            });


        });



    </script>

}

AppLaundry/AppLaundry/Views/Transaksi/Index.cshtml
@{
    ViewBag.Title = "Transaksi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="margin-top: 50px;background-color:#ffffff;padding:50px;">
    <div class="row">
        <div class="col-lg-12">
            <p>Transaksi</p>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12 col-sm-12 col-lg-2">

            <div class="card" style="margin:25px;">
                <a href="@Url.Action("CucianMasuk","Transaksi")">

                    <div class="card-body">
                        <p class="text-center">Cucian Masuk</p>
                    </div>
                    <img class="card-img-top" src="~/Assets/theme/img/in-icon.jpg" alt="Card image cap">

                </a>

            </div>
        </div>

        <div class="col-sm-12 col-sm-12 col-lg-2">
            <a href="@Url.Action("CucianKeluar","Transaksi")">

                <div class="card" style="margin:25px;">
                    <div class="card-body">
                        <p class="text-center">Cucian Keluar</p>
                    </div>
                    <img class="card-img-top" src="~/Assets/theme/img/out-icon.png" alt="Card image cap">
                </div>
            </a>

        </div>


        <div class="col-sm-12 col-sm-12 col-lg-2">

            <div class="card" style="margin:25px;">
                <a href="@Url.Action("KlaimCucian","Transaksi")">

                    <div class="card-body">
                        <p class="text-center">Claim Cucian</p>
                    </div>
                    <img class="card-img-top" src="~/Assets/theme/img/claim-icon.png" alt="Card image cap">
                </a>

            </div>

        </div>

    </div>

</div>



@section link_section{


    <!--

    Template 2108 Dashboard

    http://www.tooplate.com/view/2108-dashboard

    -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <!-- https://fonts.google.com/specimen/Open+Sans -->
    <link rel="stylesheet" href="~/Assets/theme/css/fontawesome.min.css">
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href="~/Assets/theme/css/bootstrap.min.css">
    <!-- https://getbootstrap.com/ -->

    <link rel="stylesheet" href="~/Assets/theme/css/tooplate.css">

}


@section script_section{

    <script src="~/Assets/theme/js/jquery-3.3.1.min.js"></script>
    <!-- https://jquery.com/download/ -->
    <script src="~/Assets/theme/js/bootstrap.min.js"></script>
    <!-- https://getbootstrap.com/ -->




}

AppLaundry/AppLaundry/Views/Transaksi/KlaimCucian.cshtml
@{
    ViewBag.Title = "KlaimCucian";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container" style="margin-top: 50px;background-color:#ffffff;padding:50px;">
    <div class="row">
        <div class="col-lg-12">
            <h3>List Klaim Cucian</h3>
        </div>
    </div>



</div>



@section link_section{


    <!--

    Template 2108 Dashboard

    http://www.tooplate.com/view/2108-dashboard

    -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <!-- https://fonts.google.com/specimen/Open+Sans -->
    <link rel="stylesheet" href="~/Assets/theme/css/fontawesome.min.css">
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href="~/Assets/theme/css/bootstrap.min.css">
    <!-- https://getbootstrap.com/ -->

    <link rel="stylesheet" href="~/Assets/theme/css/tooplate.css">

}


@section script_section{

    <script src="~/Assets/theme/js/jquery-3.3.1.min.js"></script>
    <!-- https://jquery.com/download/ -->
    <script src="~/Assets/theme/js/bootstrap.min.js"></script>
    <!-- https://getbootstrap.com/ -->




}